<?php
/**
 * Bamenda City Council E-Governance Platform
 * Professional Icon System
 */

/**
 * Icon mapping configuration
 */
$icon_map = [
    // Navigation Icons
    'home' => 'home',
    'dashboard' => 'dashboard',
    'services' => 'gavel',
    'business' => 'business',
    'youth' => 'school',
    'emergency' => 'emergency',
    'public_services' => 'account_balance',
    'civic_engagement' => 'groups',
    'payments' => 'payments',
    'profile' => 'person',
    'login' => 'login',
    'logout' => 'logout',
    'settings' => 'settings',
    'search' => 'search',
    'notifications' => 'notifications',
    'help_outline' => 'help_outline',
    'arrow_drop_down' => 'arrow_drop_down',
    'arrow_forward' => 'arrow_forward',
    'menu' => 'menu',
    'close' => 'close',
    
    // Service Icons
    'citizen_services' => 'gavel',
    'business_license' => 'business',
    'market_trader' => 'store',
    'property_registration' => 'domain',
    'civil_status' => 'description',
    'notary' => 'verified',
    'emergency_services' => 'emergency',
    'resources' => 'inventory_2',
    'disaster_recovery' => 'healing',
    'contacts' => 'contact_phone',
    
    // Youth Icons
    'youth_council' => 'groups',
    'employment' => 'work',
    'grants' => 'savings',
    'leadership' => 'military_tech',
    'volunteer' => 'volunteer_activism',
    'education' => 'school',
    'training' => 'school',
    
    // Admin Icons
    'users' => 'people',
    'staff' => 'badge',
    'analytics' => 'analytics',
    'reports' => 'description',
    'system' => 'settings',
    'security' => 'security',
    'backup' => 'settings_backup_restore',
    'logs' => 'history',
    
    // Status Icons
    'online' => 'check_circle',
    'offline' => 'cancel',
    'warning' => 'warning',
    'error' => 'error',
    'success' => 'check_circle',
    'pending' => 'hourglass_empty',
    'completed' => 'task_alt',
    'processing' => 'pending',
    
    // Action Icons
    'edit' => 'edit',
    'delete' => 'delete',
    'download' => 'download',
    'upload' => 'upload',
    'view' => 'visibility',
    'add' => 'add',
    'remove' => 'remove',
    'save' => 'save',
    'cancel' => 'cancel',
    'submit' => 'send',
    'refresh' => 'refresh',
    'export' => 'download',
    'print' => 'print',
    'share' => 'share',
    'copy' => 'content_copy',
    'move' => 'open_with',
    
    // Communication Icons
    'phone' => 'call',
    'email' => 'email',
    'message' => 'chat',
    'calendar' => 'calendar_today',
    'time' => 'schedule',
    'location' => 'location_on',
    'map' => 'map',
    'directions' => 'directions',
    'transport' => 'directions_bus',
    
    // File Icons
    'file' => 'description',
    'folder' => 'folder',
    'folder_open' => 'folder_open',
    'document' => 'description',
    'pdf' => 'picture_as_pdf',
    'image' => 'image',
    'video' => 'videocam',
    'audio' => 'audio_file',
    'archive' => 'archive',
    'zip' => 'folder_zip',
    
    // UI Icons
    'star' => 'star',
    'favorite' => 'favorite',
    'bookmark' => 'bookmark',
    'flag' => 'flag',
    'thumb_up' => 'thumb_up',
    'thumb_down' => 'thumb_down',
    'heart' => 'favorite',
    'share' => 'share',
    'link' => 'link',
    
    // Financial Icons
    'payments' => 'payments',
    'credit_card' => 'credit_card',
    'account_balance' => 'account_balance',
    'savings' => 'savings',
    'receipt' => 'receipt_long',
    'invoice' => 'description',
    'calculator' => 'calculate',
    'trending_up' => 'trending_up',
    'trending_down' => 'trending_down',
    'show_chart' => 'show_chart',
    
    // Security Icons
    'lock' => 'lock',
    'lock_open' => 'lock_open',
    'key' => 'key',
    'shield' => 'security',
    'privacy' => 'privacy_tip',
    'admin_panel_settings' => 'admin_panel_settings',
    'gpp_good' => 'gpp_good',
    'gpp_maybe' => 'gpp_maybe',
    'no_encryption' => 'no_encryption',
    
    // Time Icons
    'schedule' => 'schedule',
    'history' => 'history',
    'clock' => 'schedule',
    'alarm' => 'alarm',
    'timer' => 'timer',
    'hourglass_empty' => 'hourglass_empty',
    'hourglass_full' => 'hourglass_full',
    
    // Media Icons
    'play_arrow' => 'play_arrow',
    'pause' => 'pause',
    'stop' => 'stop',
    'skip_next' => 'skip_next',
    'skip_previous' => 'skip_previous',
    'replay' => 'replay',
    'volume_up' => 'volume_up',
    'volume_down' => 'volume_down',
    'volume_mute' => 'volume_mute',
    'volume_off' => 'volume_off',
    
    // Device Icons
    'desktop_windows' => 'desktop_windows',
    'laptop' => 'laptop',
    'phone' => 'smartphone',
    'tablet' => 'tablet',
    'devices' => 'devices',
    'tv' => 'tv',
    'monitor' => 'desktop_windows',
    'printer' => 'print',
    
    // Social Icons
    'public' => 'public',
    'groups' => 'groups',
    'diversity_3' => 'diversity_3',
    'people_alt' => 'people_alt',
    'person_add' => 'person_add',
    'person_remove' => 'person_remove',
    'connect_without_contact' => 'connect_without_contact',
    'share' => 'share',
    
    // Utility Icons
    'info' => 'info',
    'help' => 'help_outline',
    'support_agent' => 'support_agent',
    'feedback' => 'rate_review',
    'bug_report' => 'bug_report',
    'lightbulb' => 'lightbulb',
    'tips_and_updates' => 'tips_and_updates',
    'extension' => 'extension',
    'more_vert' => 'more_vert',
    'more_horiz' => 'more_horiz',
    'filter_list' => 'filter_list',
    'sort' => 'sort',
    'view_list' => 'view_list',
    'view_module' => 'view_module',
    'grid_view' => 'grid_view',
    'list_alt' => 'list_alt',
    
    // Status Indicators
    'circle' => 'circle',
    'check_circle' => 'check_circle',
    'cancel' => 'cancel',
    'warning' => 'warning',
    'error' => 'error',
    'priority_high' => 'priority_high',
    'warning_amber' => 'warning_amber',
    'error_outline' => 'error_outline',
    'check_circle_outline' => 'check_circle_outline',
    
    // Navigation Specific
    'menu_open' => 'menu',
    'menu_open' => 'menu_open',
    'close' => 'close',
    'expand_less' => 'expand_less',
    'expand_more' => 'expand_more',
    'unfold_less' => 'unfold_less',
    'unfold_more' => 'unfold_more',
    'subdirectory_arrow_left' => 'subdirectory_arrow_left',
    'subdirectory_arrow_right' => 'subdirectory_arrow_right',
    
    // Weather Icons
    'wb_sunny' => 'wb_sunny',
    'wb_cloudy' => 'wb_cloudy',
    'rainy' => 'rainy',
    'thunderstorm' => 'thunderstorm',
    'water_drop' => 'water_drop',
    'air' => 'air',
    'waves' => 'waves',
    'nights_stay' => 'nights_stay',
    'bedtime' => 'bedtime',
    
    // Special Purpose Icons
    'celebration' => 'celebration',
    'cake' => 'cake',
    'card_giftcard' => 'card_giftcard',
    'redeem' => 'redeem',
    'local_activity' => 'local_activity',
    'celebration' => 'celebration',
    'mood' => 'mood',
    'sentiment_satisfied' => 'sentiment_satisfied',
    'sentiment_dissatisfied' => 'sentiment_dissatisfied',
    'psychology' => 'psychology',
    'volunteer_activism' => 'volunteer_activism',
    'emoji_emotions' => 'emoji_emotions',
    'health_and_safety' => 'health_and_safety',
    'emergency_home' => 'emergency_home',
    'local_hospital' => 'local_hospital',
    'local_fire_department' => 'local_fire_department',
    'local_police' => 'local_police',
    'medical_information' => 'medical_information',
    'healing' => 'healing',
    
    // Educational Icons
    'school' => 'school',
    'menu_book' => 'menu_book',
    'auto_stories' => 'auto_stories',
    'book' => 'book',
    'bookmark' => 'bookmark',
    'history_edu' => 'history_edu',
    'psychology' => 'psychology',
    'science' => 'science',
    'biotech' => 'biotech',
    'psychology_alt' => 'psychology_alt',
    
    // Shopping and Commerce
    'shopping_cart' => 'shopping_cart',
    'store' => 'store',
    'storefront' => 'storefront',
    'shopping_bag' => 'shopping_bag',
    'local_mall' => 'local_mall',
    'point_of_sale' => 'point_of_sale',
    'receipt_long' => 'receipt_long',
    'inventory_2' => 'inventory_2',
    'sell' => 'sell',
    'attach_money' => 'attach_money',
    'payments' => 'payments',
    
    // Tools and Settings
    'build' => 'build',
    'handyman' => 'handyman',
    'construction' => 'construction',
    'plumbing' => 'plumbing',
    'electrical_services' => 'electrical_services',
    'carpenter' => 'carpenter',
    'home_repair_service' => 'home_repair_service',
    'settings' => 'settings',
    'tune' => 'tune',
    'dashboard_customize' => 'dashboard_customize',
    'account_tree' => 'account_tree',
    
    // Media and Entertainment
    'play_circle' => 'play_circle',
    'pause_circle' => 'pause_circle',
    'stop_circle' => 'stop_circle',
    'skip_next_circle' => 'skip_next_circle',
    'skip_previous_circle' => 'skip_previous_circle',
    'replay_circle' => 'replay_circle',
    'fast_forward' => 'fast_forward',
    'fast_rewind' => 'fast_rewind',
    'volume_up_circle' => 'volume_up_circle',
    'volume_down_circle' => 'volume_down_circle',
    'volume_mute_circle' => 'volume_mute_circle',
    'volume_off_circle' => 'volume_off_circle',
    
    // Communication
    'phone_in_talk' => 'phone_in_talk',
    'phone_locked' => 'phone_locked',
    'phone_missed' => 'phone_missed',
    'voicemail' => 'voicemail',
    'phone_callback' => 'phone_callback',
    'contact_phone' => 'contact_phone',
    'contact_mail' => 'contact_mail',
    'contact_page' => 'contact_page',
    'alternate_email' => 'alternate_email',
    'mark_email_unread' => 'mark_email_unread',
    'mark_email_read' => 'mark_email_read',
    'forward_to_inbox' => 'forward_to_inbox',
    
    // File Management
    'create_new_folder' => 'create_new_folder',
    'upload_file' => 'upload_file',
    'download' => 'download',
    'file_open' => 'file_open',
    'file_present' => 'file_present',
    'folder_shared' => 'folder_shared',
    'folder_special' => 'folder_special',
    'cloud_upload' => 'cloud_upload',
    'cloud_download' => 'cloud_download',
    'cloud_sync' => 'cloud_sync',
    
    // Accessibility
    'accessibility' => 'accessibility',
    'accessibility_new' => 'accessibility_new',
    'wheelchair_pickup' => 'wheelchair_pickup',
    'sign_language' => 'sign_language',
    'translate' => 'translate',
    'text_format' => 'text_format',
    'format_size' => 'format_size',
    'format_align_left' => 'format_align_left',
    'format_align_center' => 'format_align_center',
    'format_align_right' => 'format_align_right',
    'format_align_justify' => 'format_align_justify',
    
    // Security and Privacy
    'security' => 'security',
    'privacy_tip' => 'privacy_tip',
    'policy' => 'policy',
    'gpp_maybe' => 'gpp_maybe',
    'gpp_bad' => 'gpp_bad',
    'no_encryption' => 'no_encryption',
    'enhanced_encryption' => 'enhanced_encryption',
    'security_update_good' => 'security_update_good',
    'security_update_warning' => 'security_update_warning',
    'security_update_error' => 'security_update_error',
    
    // System and Performance
    'memory' => 'memory',
    'storage' => 'storage',
    'sd_storage' => 'sd_storage',
    'usb' => 'usb',
    'settings_backup_restore' => 'settings_backup_restore',
    'system_update' => 'system_update',
    'system_update_alt' => 'system_update_alt',
    'bug_report' => 'bug_report',
    'feedback' => 'feedback',
    'rate_review' => 'rate_review',
    
    // Time and Date
    'schedule' => 'schedule',
    'event' => 'event',
    'calendar_today' => 'calendar_today',
    'calendar_month' => 'calendar_month',
    'date_range' => 'date_range',
    'today' => 'today',
    'update' => 'update',
    'history' => 'history',
    'pending_actions' => 'pending_actions',
    'alarm' => 'alarm',
    'timer' => 'timer',
    'hourglass_empty' => 'hourglass_empty',
    'hourglass_full' => 'hourglass_full',
    
    // Weather and Environment
    'wb_sunny' => 'wb_sunny',
    'wb_cloudy' => 'wb_cloudy',
    'rainy' => 'rainy',
    'thunderstorm' => 'thunderstorm',
    'water_drop' => 'water_drop',
    'air' => 'air',
    'waves' => 'waves',
    'nights_stay' => 'nights_stay',
    'bedtime' => 'bedtime',
    'thermostat' => 'thermostat',
    'device_thermostat' => 'device_thermostat',
    'eco' => 'eco',
    'light_mode' => 'light_mode',
    'dark_mode' => 'dark_mode',
    'brightness_auto' => 'brightness_auto',
    'brightness_high' => 'brightness_high',
    'brightness_low' => 'brightness_low',
    'brightness_medium' => 'brightness_medium',
    
    // Transportation
    'directions' => 'directions',
    'directions_bus' => 'directions_bus',
    'directions_car' => 'directions_car',
    'directions_walk' => 'directions_walk',
    'directions_bike' => 'directions_bike',
    'directions_railway' => 'directions_railway',
    'directions_subway' => 'directions_subway',
    'directions_ferry' => 'directions_ferry',
    'local_taxi' => 'local_taxi',
    'ev_station' => 'ev_station',
    'map' => 'map',
    'location_on' => 'location_on',
    'edit_location' => 'edit_location',
    'my_location' => 'my_location',
    'near_me' => 'near_me',
    
    // Health and Medical
    'medical_services' => 'medical_services',
    'local_hospital' => 'local_hospital',
    'local_pharmacy' => 'local_pharmacy',
    'medical_information' => 'medical_information',
    'health_and_safety' => 'health_and_safety',
    'healing' => 'healing',
    'monitor_heart' => 'monitor_heart',
    'fitness_center' => 'fitness_center',
    'self_improvement' => 'self_improvement',
    'psychology' => 'psychology',
    'medication' => 'medication',
    'vaccines' => 'vaccines',
    'emergency_home' => 'emergency_home',
    
    // Food and Dining
    'restaurant' => 'restaurant',
    'local_cafe' => 'local_cafe',
    'local_bar' => 'local_bar',
    'local_pizza' => 'local_pizza',
    'grocery_store' => 'grocery_store',
    'shopping_cart' => 'shopping_cart',
    'store' => 'store',
    'storefront' => 'storefront',
    'delivery_dining' => 'delivery_dining',
    'takeout_dining' => 'takeout_dining',
    'food_bank' => 'food_bank',
    'free_breakfast' => 'free_breakfast',
    'lunch_dining' => 'lunch_dining',
    'dinner_dining' => 'dinner_dining',
    
    // Sports and Recreation
    'sports_soccer' => 'sports_soccer',
    'sports_basketball' => 'sports_basketball',
    'sports_tennis' => 'sports_tennis',
    'sports_football' => 'sports_football',
    'fitness_center' => 'fitness_center',
    'pool' => 'pool',
    'spa' => 'spa',
    'golf_course' => 'golf_course',
    'stadium' => 'stadium',
    'theater_comedy' => 'theater_comedy',
    'nightlife' => 'nightlife',
    'festival' => 'festival',
    'celebration' => 'celebration',
    
    // Travel and Tourism
    'flight' => 'flight',
    'hotel' => 'hotel',
    'luggage' => 'luggage',
    'map' => 'map',
    'location_on' => 'location_on',
    'tour' => 'tour',
    'museum' => 'museum',
    'beach_access' => 'beach_access',
    'forest' => 'forest',
    'mountain' => 'mountain',
    'camping' => 'camping',
    'hiking' => 'hiking',
    'bike_scooter' => 'bike_scooter',
    'sailing' => 'sailing',
    'kayaking' => 'kayaking',
    
    // Shopping and Commerce
    'shopping_bag' => 'shopping_bag',
    'shopping_cart' => 'shopping_cart',
    'local_mall' => 'local_mall',
    'point_of_sale' => 'point_of_sale',
    'receipt_long' => 'receipt_long',
    'inventory_2' => 'inventory_2',
    'sell' => 'sell',
    'attach_money' => 'attach_money',
    'payments' => 'payments',
    'credit_card' => 'credit_card',
    'account_balance' => 'account_balance',
    'savings' => 'savings',
    
    // Miscellaneous
    'more_horiz' => 'more_horiz',
    'more_vert' => 'more_vert',
    'expand_less' => 'expand_less',
    'expand_more' => 'expand_more',
    'unfold_less' => 'unfold_less',
    'unfold_more' => 'unfold_more',
    'filter_list' => 'filter_list',
    'sort' => 'sort',
    'view_list' => 'view_list',
    'view_module' => 'view_module',
    'grid_view' => 'grid_view',
    'list_alt' => 'list_alt',
    'dashboard' => 'dashboard',
    'view_quilt' => 'view_quilt',
    'view_agenda' => 'view_agenda',
    'view_comfy' => 'view_comfy',
    'view_comfy_alt' => 'view_comfy_alt',
    'view_carousel' => 'view_carousel',
    'view_day' => 'view_day',
    'view_week' => 'view_week',
    'view_module' => 'view_module',
    'view_stream' => 'view_stream',
    'view_timeline' => 'view_timeline',
    
    // Brand and Identity
    'branding_watermark' => 'branding_watermark',
    'fingerprint' => 'fingerprint',
    'face' => 'face',
    'face_retouching_natural' => 'face_retouching_natural',
    'face_retouching_off' => 'face_retouching_off',
    'filter_drama' => 'filter_drama',
    'filter_frames' => 'filter_frames',
    'filter_vintage' => 'filter_vintage',
    'filter_b_and_w' => 'filter_b_and_w',
    'filter_none' => 'filter_none',
    'blur_on' => 'blur_on',
    'blur_off' => 'blur_off',
    'auto_fix_high' => 'auto_fix_high',
    'auto_fix_off' => 'auto_fix_off',
    'portrait' => 'portrait',
    'landscape' => 'landscape',
    'flip_camera_android' => 'flip_camera_android',
    'flip_camera_ios' => 'flip_camera_ios',
    'camera_alt' => 'camera_alt',
    'photo_camera' => 'photo_camera',
    'photo_filter' => 'photo_filter',
    'photo_size_select_actual' => 'photo_size_select_actual',
    'photo_size_select_large' => 'photo_size_select_large',
    'photo_size_select_small' => 'photo_size_select_small',
    
    // Audio and Video
    'music_note' => 'music_note',
    'music_off' => 'music_off',
    'play_circle' => 'play_circle',
    'pause_circle' => 'pause_circle',
    'stop_circle' => 'stop_circle',
    'skip_next_circle' => 'skip_next_circle',
    'skip_previous_circle' => 'skip_previous_circle',
    'replay_circle' => 'replay_circle',
    'volume_up_circle' => 'volume_up_circle',
    'volume_down_circle' => 'volume_down_circle',
    'volume_mute_circle' => 'volume_mute_circle',
    'volume_off_circle' => 'volume_off_circle',
    'videocam' => 'videocam',
    'videocam_off' => 'videocam_off',
    'camera' => 'camera',
    'camera_alt' => 'camera_alt',
    'image' => 'image',
    'image_search' => 'image_search',
    'high_quality' => 'high_quality',
    'hd' => 'hd',
    '4k' => '4k',
    'slow_motion_video' => 'slow_motion_video',
    'video_settings' => 'video_settings',
    'video_file' => 'video_file',
    'video_library' => 'video_library',
    'live_tv' => 'live_tv',
    'personal_video' => 'personal_video',
    'subscriptions' => 'subscriptions',
    
    // Social and Communication
    'chat' => 'chat',
    'chat_bubble' => 'chat_bubble',
    'chat_bubble_outline' => 'chat_bubble_outline',
    'forum' => 'forum',
    'groups' => 'groups',
    'diversity_3' => 'diversity_3',
    'people_alt' => 'people_alt',
    'person_add' => 'person_add',
    'person_remove' => 'person_remove',
    'connect_without_contact' => 'connect_without_contact',
    'share' => 'share',
    'public' => 'public',
    'send' => 'send',
    'drafts' => 'drafts',
    'inbox' => 'inbox',
    'all_inbox' => 'all_inbox',
    'send' => 'send',
    'mark_email_unread' => 'mark_email_unread',
    'mark_email_read' => 'mark_email_read',
    'forward_to_inbox' => 'forward_to_inbox',
    'label' => 'label',
    'label_important' => 'label_important',
    'labels' => 'labels',
    
    // Files and Storage
    'folder' => 'folder',
    'folder_open' => 'folder_open',
    'folder_shared' => 'folder_shared',
    'folder_special' => 'folder_special',
    'create_new_folder' => 'create_new_folder',
    'upload_file' => 'upload_file',
    'download' => 'download',
    'file_open' => 'file_open',
    'file_present' => 'file_present',
    'cloud_upload' => 'cloud_upload',
    'cloud_download' => 'cloud_download',
    'cloud_sync' => 'cloud_sync',
    'cloud_done' => 'cloud_done',
    'cloud_off' => 'cloud_off',
    'cloud_queue' => 'cloud_queue',
    'cloud_circle' => 'cloud_circle',
    'backup' => 'backup',
    'restore' => 'restore',
    'settings_backup_restore' => 'settings_backup_restore',
    'storage' => 'storage',
    'sd_storage' => 'sd_storage',
    'usb' => 'usb',
    'hard_drive' => 'hard_drive',
    'sim_card' => 'sim_card',
    'phone_android' => 'phone_android',
    'phone_iphone' => 'phone_iphone',
    'devices' => 'devices',
    'devices_other' => 'devices_other',
    'computer' => 'computer',
    'desktop_windows' => 'desktop_windows',
    'laptop' => 'laptop',
    'tablet' => 'tablet',
    'smartphone' => 'smartphone',
    'monitor' => 'monitor',
    'tv' => 'tv',
    'device_unknown' => 'device_unknown',
    
    // Settings and System
    'settings' => 'settings',
    'tune' => 'tune',
    'dashboard_customize' => 'dashboard_customize',
    'account_tree' => 'account_tree',
    'app_settings' => 'app_settings',
    'app_registration' => 'app_registration',
    'system_update' => 'system_update',
    'system_update_alt' => 'system_update_alt',
    'security' => 'security',
    'privacy_tip' => 'privacy_tip',
    'policy' => 'policy',
    'gpp_maybe' => 'gpp_maybe',
    'gpp_bad' => 'gpp_bad',
    'no_encryption' => 'no_encryption',
    'enhanced_encryption' => 'enhanced_encryption',
    'security_update_good' => 'security_update_good',
    'security_update_warning' => 'security_update_warning',
    'security_update_error' => 'security_update_error',
    'notifications' => 'notifications',
    'notifications_active' => 'notifications_active',
    'notifications_none' => 'notifications_none',
    'notifications_paused' => 'notifications_paused',
    'notifications_off' => 'notifications_off',
    'snooze' => 'snooze',
    'alarm' => 'alarm',
    'alarm_off' => 'alarm_off',
    'timer' => 'timer',
    'schedule' => 'schedule',
    'event' => 'event',
    'calendar_today' => 'calendar_today',
    'calendar_month' => 'calendar_month',
    'date_range' => 'date_range',
    'today' => 'today',
    'update' => 'update',
    'history' => 'history',
    'pending_actions' => 'pending_actions',
    'hourglass_empty' => 'hourglass_empty',
    'hourglass_full' => 'hourglass_full'
];

/**
 * Render icon function
 */
function render_icon($icon_key, $class = '', $size = '24px', $color = '') {
    $icon_name = $icon_map[$icon_key] ?? 'help_outline';
    
    $size_map = [
        '16px' => '16',
        '20px' => '20',
        '24px' => '24',
        '32px' => '32',
        '48px' => '48',
        '64px' => '64'
    ];
    
    $size_class = $size_map[$size] ?? '24';
    
    return '<span class="material-symbols-outlined ' . $class . '" style="font-size: ' . $size . '; color: ' . $color . ';">' . $icon_name . '</span>';
}

/**
 * Get icon by category
 */
function get_icons_by_category($category) {
    $categories = [
        'navigation' => ['home', 'dashboard', 'services', 'business', 'youth', 'emergency', 'public_services', 'civic_engagement', 'payments', 'profile', 'login', 'logout', 'settings', 'search', 'notifications', 'help_outline', 'arrow_drop_down', 'arrow_forward', 'menu', 'close'],
        'services' => ['citizen_services', 'business_license', 'market_trader', 'property_registration', 'civil_status', 'notary', 'emergency_services', 'resources', 'disaster_recovery', 'contacts'],
        'youth' => ['youth_council', 'employment', 'grants', 'leadership', 'volunteer', 'education', 'training'],
        'admin' => ['users', 'staff', 'analytics', 'reports', 'system', 'security', 'backup', 'logs'],
        'status' => ['online', 'offline', 'warning', 'error', 'success', 'pending', 'completed', 'processing'],
        'actions' => ['edit', 'delete', 'download', 'upload', 'view', 'add', 'remove', 'save', 'cancel', 'submit', 'refresh', 'export', 'print', 'share', 'copy', 'move'],
        'communication' => ['phone', 'email', 'message', 'calendar_today', 'time', 'location_on', 'map', 'directions', 'transport'],
        'files' => ['file', 'folder', 'folder_open', 'document', 'pdf', 'image', 'video', 'audio', 'archive', 'zip'],
        'ui' => ['star', 'favorite', 'bookmark', 'flag', 'thumb_up', 'thumb_down', 'heart', 'share', 'link'],
        'financial' => ['payments', 'credit_card', 'account_balance', 'savings', 'receipt', 'invoice', 'calculator', 'trending_up', 'trending_down', 'show_chart'],
        'security' => ['lock', 'lock_open', 'key', 'shield', 'privacy_tip', 'admin_panel_settings', 'gpp_good', 'gpp_maybe', 'no_encryption', 'enhanced_encryption', 'security_update_good', 'security_update_warning', 'security_update_error'],
        'time' => ['schedule', 'history', 'clock', 'alarm', 'timer', 'hourglass_empty', 'hourglass_full'],
        'media' => ['play_arrow', 'pause', 'stop', 'skip_next', 'skip_previous', 'replay', 'fast_forward', 'fast_rewind', 'volume_up', 'volume_down', 'volume_mute', 'volume_off'],
        'accessibility' => ['accessibility', 'accessibility_new', 'wheelchair_pickup', 'sign_language', 'translate', 'text_format', 'format_size', 'format_align_left', 'format_align_center', 'format_align_right', 'format_align_justify'],
        'weather' => ['wb_sunny', 'wb_cloudy', 'rainy', 'thunderstorm', 'water_drop', 'air', 'waves', 'nights_stay', 'bedtime'],
        'transportation' => ['directions', 'directions_bus', 'directions_car', 'directions_walk', 'directions_bike', 'directions_railway', 'directions_subway', 'directions_ferry', 'local_taxi', 'ev_station', 'map', 'location_on', 'edit_location', 'my_location', 'near_me'],
        'health' => ['medical_services', 'local_hospital', 'local_pharmacy', 'medical_information', 'health_and_safety', 'healing', 'monitor_heart', 'fitness_center', 'self_improvement', 'psychology', 'medication', 'vaccines', 'emergency_home'],
        'shopping' => ['restaurant', 'local_cafe', 'local_bar', 'local_pizza', 'grocery_store', 'shopping_cart', 'store', 'storefront', 'delivery_dining', 'takeout_dining', 'food_bank', 'free_breakfast', 'lunch_dining', 'dinner_dining'],
        'sports' => ['sports_soccer', 'sports_basketball', 'sports_tennis', 'sports_football', 'fitness_center', 'pool', 'spa', 'golf_course', 'stadium', 'theater_comedy', 'nightlife', 'festival'],
        'travel' => ['flight', 'hotel', 'luggage', 'map', 'location_on', 'tour', 'museum', 'beach_access', 'forest', 'mountain', 'camping', 'hiking', 'bike_scooter', 'sailing', 'kayaking'],
        'miscellaneous' => ['more_horiz', 'more_vert', 'expand_less', 'expand_more', 'unfold_less', 'unfold_more', 'filter_list', 'sort', 'view_list', 'view_module', 'grid_view', 'list_alt']
    ];
    
    return $categories[$category] ?? [];
}
?>
